

  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 50

  left_wheel: ['joint_left_wheel_front','joint_left_wheel_back']
  right_wheel: ['joint_right_wheel_front','joint_right_wheel_back']

  wheel_separation: 0.44

  # Odometry covariances for the encoder output of the robot. These values should
  # be tuned to your robot's sample odometry data, but these values are a good place
  # to start
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

  # Top level frame (link) of the robot description
  base_frame_id: link_chassis

  # Velocity and acceleration limits for the robot
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.6   # m/s^2
  angular:
    z:
      has_velocity_limits    : false
      # max_velocity           : 20   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0   # rad/s^2